services:
  - type: web
    name: shark-api
    runtime: docker
    plan: free
    dockerfilePath: ./Shark-api-go/Dockerfile
    dockerContext: ./Shark-api-go
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: PORT
        value: 8080
